### ISSUE TITLE
This might have tanked my machine

### ISSUE THREAD

**Issue by KeironO** [jamesaaron97248/sysclean-sesc191y#1]
Hey there,

I saw this posted on the ArchLinux subreddit last night and was interested in using it as I find post-install/upgrade stuff does tend to involve a lot of cleaning up for my system as I've had this install since late 2015.

However, when I ran it this morning I noticed that my box started running slowly so I restarted - to a blinking cursor.

I've managed to get the system back to the point that I can list packages, and it looks like this has inadvertently deleted everything that isn't a direct dependency. The problem here is that not all stuff packaged for Arch has dependencies explicitly defined, so this script is kind of dangerous.

BW,

Keiron

**Comment by KeironO** [comment]
Oh, I just realised that you've already fixed the problem - I made the git pull last night before bed!

Silly me!

**Comment by jamesaaron97248** [comment]
> Hey there,
> 
> I saw this posted on the ArchLinux subreddit last night and was interested in using it as I find post-install/upgrade stuff does tend to involve a lot of cleaning up for my system as I've had this install since late 2015.
> 
> However, when I ran it this morning I noticed that my box started running slowly so I restarted - to a blinking cursor.
> 
> I've managed to get the system back to the point that I can list packages, and it looks like this has inadvertently deleted everything that isn't a direct dependency. The problem here is that not all stuff packaged for Arch has dependencies explicitly defined, so this script is kind of dangerous.
> 
> BW,
> 
> Keiron

I'm sorry to here that. I thought the command does not work due to the space in - Rns flag. Still I'm very sorry to here that, I'm sorry. I already did fixed the issue, thanks for pointing out!
